packages:
  - "docs"
  - "playground"

onlyBuiltDependencies:
  - better-sqlite3
  - sharp

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
